"""empty message

Revision ID: c3003013bece
Revises: b90095781f01
Create Date: 2022-01-20 21:55:06.838965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3003013bece'
down_revision = 'b90095781f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('title', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'title')
    # ### end Alembic commands ###
